- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial (548b8965-27d7-4018-a650-9a9a77106324)'
    azureContainerRegistry: '{"loginServer":"dataacr1113.azurecr.io", "id" : "/subscriptions/548b8965-27d7-4018-a650-9a9a77106324/resourceGroups/data-ci-cd/providers/Microsoft.ContainerRegistry/registries/dataacr1113"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'